### ISSUE TITLE
Establish Coding Standard

### ISSUE THREAD

**Issue by samuelmenkus** [samuelmenkus/freeze-laser-tag#1]
Figure out which coding standard we want to use; Unreal has a C++ standard that they recommend, which I figure we'll use. This will likely also include some discussion of Git best practices.

**Comment by wmenkus** [comment]
Unreal's coding standard:

https://dev.epicgames.com/documentation/en-us/unreal-engine/epic-cplusplus-coding-standard-for-unreal-engine

**Comment by wmenkus** [comment]
We should also discuss naming conventions for Blueprint

**Comment by wmenkus** [comment]
https://dev.epicgames.com/documentation/en-us/unreal-engine/recommended-asset-naming-conventions-in-unreal-engine-projects

**Comment by wmenkus** [comment]
https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53
